/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited manually.
// It is auto-generated by the Next.js TypeScript compiler for IntelliSense,
// global type support, and Image Optimization types.

// Additional custom global types can be added in `types/index.ts` instead.
