export const templates = [
  {
    industry: 'Coaches & Consultants',
    templates: [
      {
        title: 'Launch Pad Website',
        slug: 'launch-pad-website',
        demoUrl: 'https://launch-pad-demo.vercel.app',
        description: 'For solo coaches launching a new offer or lead magnet.',
        industry: 'Coaches & Consultants',
        features: [
          '1-page conversion-optimized layout',
          'Email capture with Mailchimp integration',
          'Mobile responsive design with call-to-action',
        ],
        useCase: 'Great for early-stage coaches validating a new offer.',
        price: '$500–$1,000',
      },
      {
        title: 'Funnel Builder',
        slug: 'funnel-builder',
        demoUrl: 'https://funnel-builder-demo.vercel.app',
        description: 'Multi-step opt-in flows with email integration + CRM.',
        industry: 'Coaches & Consultants',
        features: [
          'Multi-page funnel with lead magnet landing',
          'Email service provider integration (Mailchimp, ConvertKit)',
          'Automated thank-you and follow-up pages',
        ],
        useCase: 'For creators and consultants looking to build automated pipelines.',
        price: '$1,000–$2,000',
      },
      {
        title: 'Authority Platform',
        slug: 'authority-platform',
        demoUrl: 'https://authority-platform-demo.vercel.app',
        description: 'Content hub, booking system, and scaling workflows.',
        industry: 'Coaches & Consultants',
        features: [
          'Resource/blog CMS with categories',
          'Client booking with Calendly integration',
          'Custom workflows for nurturing leads and sessions',
        ],
        useCase: 'For experienced coaches building a full-service presence.',
        price: '$3,000–$5,000',
      },
    ],
  },
  {
    industry: 'Bootstrapped SaaS',
    templates: [
      {
        title: 'Startup Landing Page',
        slug: 'startup-landing-page',
        demoUrl: 'https://startup-landing-demo.vercel.app',
        description: 'One-page MVP with founder-friendly copy + analytics.',
        industry: 'Bootstrapped SaaS',
        features: [
          'Clear product value prop layout',
          'Founding team CTA section',
          'GA + Hotjar setup baked in',
        ],
        useCase: 'For bootstrapped founders testing MVP traction.',
        price: '$500–$1,200',
      },
      {
        title: 'Marketing Site + Funnel',
        slug: 'marketing-site-funnel',
        demoUrl: 'https://marketing-funnel-demo.vercel.app',
        description: 'Product pages, use-case funnels, and email sequences.',
        industry: 'Bootstrapped SaaS',
        features: [
          'Use-case breakdown landing pages',
          'Email opt-in and onboarding sequences',
          'Lead scoring workflow readiness',
        ],
        useCase: 'For scaling startups needing top-of-funnel optimization.',
        price: '$2,000–$2,500',
      },
      {
        title: 'Growth Engine',
        slug: 'growth-engine',
        demoUrl: 'https://growth-engine-demo.vercel.app',
        description: 'Blog, SEO, retargeting pixels, and post-signup workflows.',
        industry: 'Bootstrapped SaaS',
        features: [
          'SEO-optimized blog system (CMS)',
          'Signup CTA and retargeting infrastructure',
          'Lifecycle marketing integrations',
        ],
        useCase: 'Ideal for post-Series A SaaS teams focused on growth loops.',
        price: '$4,000–$6,000',
      },
    ],
  },
  {
    industry: 'Local Service Providers',
    templates: [
      {
        title: 'Lead Capture Page',
        slug: 'lead-capture-page',
        demoUrl: 'https://lead-capture-demo.vercel.app',
        description: 'Mobile-friendly page with form + click-to-call.',
        industry: 'Local Service Providers',
        features: [
          'Local SEO and Google Maps section',
          'Tap-to-call and mobile form submission',
          'Trust badges and testimonials block',
        ],
        useCase: 'Built for plumbers, dentists, and service pros needing leads.',
        price: '$500–$1,200',
      },
      {
        title: 'Mini Funnel + Booking',
        slug: 'mini-funnel-booking',
        demoUrl: 'https://mini-funnel-demo.vercel.app',
        description: 'Simple opt-in → confirmation flow + calendar integration.',
        industry: 'Local Service Providers',
        features: [
          'Opt-in incentive or service pitch form',
          'Booking automation with Calendly/Google Calendar',
          'Confirmation thank-you page',
        ],
        useCase: 'Ideal for solo providers running appointment funnels.',
        price: '$1,000–$1,800',
      },
      {
        title: 'Full Local SEO System',
        slug: 'full-local-seo-system',
        demoUrl: 'https://seo-system-demo.vercel.app',
        description: 'Pages for each service, city, reviews + tracking.',
        industry: 'Local Service Providers',
        features: [
          'Service-area landing pages with schema markup',
          'Embedded reviews/testimonials widgets',
          'Google Analytics + lead tracking setup',
        ],
        useCase: 'For service businesses targeting multiple local markets.',
        price: '$2,500–$4,000',
      },
    ],
  },
];
