// content/pricing.ts

export const pricing = [
  {
    category: "Web Development",
    headline: "From MVP to investor-ready — launch fast, scale smart.",
    tiers: [
      {
        title: "Launch Fast",
        price: "$1,490",
        highlight: false,
        description: "Get live in 7 days with a polished, conversion-ready MVP.",
        features: [
          "1-page or MVP site",
          "Mobile-first responsive design",
          "Lead capture + contact form",
          "Core brand styling",
          "Fast delivery (7 days avg)",
        ],
        cta: "Launch My Site",
        badge: "Best for early-stage founders",
      },
      {
        title: "Conversion Engine",
        price: "$3,500",
        highlight: true,
        description: "Your site becomes a funnel — designed to scale traffic and leads.",
        features: [
          "Multi-page CMS website",
          "CRM + email integration",
          "Custom animations + scroll logic",
          "SEO + speed optimized",
          "Conversion-first UX copy",
        ],
        cta: "Build My Funnel",
        badge: "Most Popular",
      },
      {
        title: "Investor Magnet",
        price: "$6,000+",
        highlight: false,
        description: "A flagship site that turns heads and secures funding.",
        features: [
          "6+ pages with premium layout",
          "Full UI/UX polish + advanced animations",
          "CMS with custom API hooks",
          "Interactive components",
          "Investor-ready presentation layer",
        ],
        cta: "Go Enterprise",
        badge: "Built for funded startups",
      },
    ],
  },
  {
    category: "Systems That Scale",
    headline: "Automation + infrastructure to grow like a $10M company.",
    tiers: [
      {
        title: "Automate & Save",
        price: "$2,500",
        highlight: false,
        description: "Start saving 20+ hours/month with smart automations.",
        features: [
          "CRM setup (GoHighLevel, HubSpot, or Notion)",
          "Email nurture flows",
          "Lead intake automation",
          "2 Zapier/Make workflows",
          "Basic team SOPs",
        ],
        cta: "Start Automating",
        badge: "Best for solo operators",
      },
      {
        title: "Growth Stack",
        price: "$6,400",
        highlight: true,
        description: "Your operating system for revenue, hiring, and scale.",
        features: [
          "Sales & marketing CRM buildout",
          "Funnel tracking dashboards",
          "Hiring + onboarding systems",
          "Team Notion workspace + SOPs",
          "Automation across 4+ departments",
        ],
        cta: "Build My Stack",
        badge: "Most Popular",
      },
      {
        title: "Founder's OS",
        price: "$12,000+",
        highlight: false,
        description: "Custom stack, investor-ready architecture, and scale support.",
        features: [
          "Custom Retool/Airtable/Make dashboards",
          "Slack, CRM, Notion + hiring integrations",
          "Advanced permissioning + roles",
          "Team training & onboarding materials",
          "Investor-grade tech ops design",
        ],
        cta: "Systemize It All",
        badge: "Built for funded teams",
      },
    ],
  },
  {
    category: "Growth Retainers",
    headline: "Ongoing optimization to keep your digital engine compounding.",
    tiers: [
      {
        title: "Site Support",
        price: "$500/mo",
        highlight: false,
        description: "Keep your site updated and always sharp.",
        features: [
          "Monthly content edits",
          "CRO tweak (1/month)",
          "Performance monitoring",
          "Speed & SEO checkups",
          "Priority support access",
        ],
        cta: "Keep Me Updated",
        badge: "Perfect for static sites",
      },
      {
        title: "Growth Optimization",
        price: "$1,000/mo",
        highlight: true,
        description: "Ongoing CRO, testing, and updates that drive conversion growth.",
        features: [
          "Bi-weekly A/B testing",
          "2+ monthly CRO updates",
          "Quarterly UX refreshes",
          "Analytics dashboard setup",
          "Conversion reporting",
        ],
        cta: "Optimize My Growth",
        badge: "Most Popular",
      },
      {
        title: "Revenue Partner",
        price: "$2,000+/mo",
        highlight: false,
        description: "Full partnership model for conversion, funnel, and MRR growth.",
        features: [
          "Unlimited site edits",
          "Weekly strategy sessions",
          "Performance + ROI dashboards",
          "Revenue-focused design upgrades",
          "Quarterly funnel rebuilds",
        ],
        cta: "Be My Partner",
        badge: "Trusted by $1M+ teams",
      },
    ],
  },
];
